#ifndef GROCERYSTORE_PRODUCT_H
#define GROCERYSTORE_PRODUCT_H

#include <string>
#include <utility>
#include "vat.h"
#include "category.h"
#include "profitmargin.h"


class Product  {
public:
    Product(){};

    Product(std::string newProductName,
            Category newProductCategory,
            Vat newProductVat,
            float newWholeSalePrice,
            ProfitMargin newProductProfitMargin) :
            productName(std::move(newProductName)),
            category(newProductCategory),
            vat(newProductVat),
            wholeSalePrice(newWholeSalePrice),
            margin(newProductProfitMargin){}

    void addNewProduct(Product product);
    //void updateWholeSalePrice(int productID, float newWholeSalePrice);


    std::string getName();
    int getVat();
    int getProfitMargin();
    float getWholeSalePrice();
    int getInStock();
    float generateRetailPrice();

protected:
    std::string productName;
    float retailPrice; // autogenerated based on wholesaleprice vat and profitmargin
    float wholeSalePrice;
    int inStock = 0;
    Category category;
    Vat vat;
    ProfitMargin margin;
};


#endif //GROCERYSTORE_PRODUCT_H
