#ifndef GROCERYSTORE_PRODUCT_H
#define GROCERYSTORE_PRODUCT_H

#include <string>
#include <utility>
#include "vat.h"
#include "category.h"
#include "profitmargin.h"


class Product  {
public:
    Product(std::string newProductName,
            Category newProductCategory,
            Vat newProductVat,
            ProfitMargin newProductProfitMargin) :
            productName(std::move(newProductName)),
            category(newProductCategory),
            vat(newProductVat),
            margin(newProductProfitMargin){}

    void addNewProduct(Product product);
    void updateWholeSalePrice(int productID, float newWholeSalePrice);
    std::string categoryToString(Category category);
    std::string getName();
    Vat getVat();
    ProfitMargin getProfitMargin();

protected:
    std::string productName;
    float retailPrice; // autogenerated wholesalePrice * vat * margin
    float wholesalePrice;
    int inStock;
    Category category;
    Vat vat;
    ProfitMargin margin;
};


#endif //GROCERYSTORE_PRODUCT_H
